"""modules_1_to_10_schema

Revision ID: 49a711d3f09e
Revises: 
Create Date: 2026-06-23 05:15:44.414239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a711d3f09e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BANK_STAFF', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'APPROVED', 'REVIEW_REQUIRED', 'REJECTED', name='kyc_status'), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_case_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('face_match_pct', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_document_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_case_id', sa.UUID(), nullable=False),
    sa.Column('name_match_score', sa.Float(), nullable=False),
    sa.Column('dob_match', sa.Boolean(), nullable=False),
    sa.Column('gender_match', sa.Boolean(), nullable=True),
    sa.Column('overall_match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_case_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('AADHAAR', 'PAN', 'SELFIE', name='document_type'), nullable=False),
    sa.Column('r2_object_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_case_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kyc_case_id')
    )
    op.create_table('liveness_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_case_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('LIVE', 'SPOOF', 'INCONCLUSIVE', name='liveness_verdict'), nullable=False),
    sa.Column('blink_detected', sa.Boolean(), nullable=False),
    sa.Column('head_movement_detected', sa.Boolean(), nullable=False),
    sa.Column('smile_detected', sa.Boolean(), nullable=False),
    sa.Column('max_yaw_delta_degrees', sa.Float(), nullable=False),
    sa.Column('total_frames_analyzed', sa.Integer(), nullable=False),
    sa.Column('frames_with_face', sa.Integer(), nullable=False),
    sa.Column('frames_without_face', sa.Integer(), nullable=False),
    sa.Column('raw_metrics_json', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kyc_case_id')
    )
    op.create_table('face_verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kyc_case_id', sa.UUID(), nullable=False),
    sa.Column('id_document_id', sa.UUID(), nullable=False),
    sa.Column('selfie_document_id', sa.UUID(), nullable=False),
    sa.Column('cosine_similarity', sa.Float(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=False),
    sa.Column('is_match', sa.Boolean(), nullable=False),
    sa.Column('detector_backend', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selfie_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extracted_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_dob', sa.String(length=20), nullable=True),
    sa.Column('extracted_gender', sa.String(length=20), nullable=True),
    sa.Column('extracted_address', sa.Text(), nullable=True),
    sa.Column('extracted_aadhaar_no', sa.String(length=20), nullable=True),
    sa.Column('extracted_pan_no', sa.String(length=20), nullable=True),
    sa.Column('raw_ocr_json', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('tampering_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('REAL', 'TAMPERED', 'INCONCLUSIVE', name='tamper_verdict'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ela_score', sa.Float(), nullable=False),
    sa.Column('resnet_feature_vector_ref', sa.String(length=512), nullable=True),
    sa.Column('gradcam_heatmap_r2_key', sa.String(length=512), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tampering_results')
    op.drop_table('ocr_extractions')
    op.drop_table('face_verification_results')
    op.drop_table('liveness_results')
    op.drop_table('fraud_risk_scores')
    op.drop_table('documents')
    op.drop_table('cross_document_results')
    op.drop_table('chat_messages')
    op.drop_table('audit_logs')
    op.drop_table('kyc_cases')
    op.drop_table('chat_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
