"""enforce audit_logs insert-only via REVOKE

This migration is HAND-WRITTEN, not autogenerated — SQLAlchemy's ORM and
Alembic's autogenerate diffing have no concept of GRANT/REVOKE privileges,
since those are a database-level access-control feature, not part of a
table's structural schema. This is the only mechanism that makes
"audit_logs is insert-only" a real, enforced guarantee rather than a
comment/convention that any future bug or careless developer could
violate.

PREREQUISITE: this migration must be applied AFTER the initial schema
migration that creates the audit_logs table. Run:

    alembic revision --autogenerate -m "initial schema"

against a real Postgres database first (this sandbox has no Postgres
available, so that initial migration must be generated by you in
Docker/local — see Module 9 delivery notes). Then update this file's
`down_revision` value below to match the revision ID Alembic assigns to
that initial migration, and run `alembic upgrade head` to apply both in
order.

WHAT THIS DOES:
  1. REVOKEs UPDATE and DELETE on audit_logs from the application's
     database role (read from DATABASE_URL's connection user — see
     note below on role name assumptions).
  2. Leaves INSERT and SELECT untouched, since the application must
     still be able to write new audit entries and read them back for
     the Admin Dashboard (Module 11).

ROLE NAME ASSUMPTION: this migration revokes privileges from the
*current connected role* (Postgres's CURRENT_USER), which is whatever
role DATABASE_URL authenticates as. This is the simplest correct
approach for a single-application-role deployment (the common case for
this project). If your deployment uses a SEPARATE, more-privileged
migration role distinct from the application's runtime role (a stronger
security posture, but not yet a decision this project has locked), this
migration would need to target that runtime role's name explicitly
instead of CURRENT_USER — flagging this now rather than silently
assuming the simpler single-role setup is what you'll deploy.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a9c3d7e2b4"
# IMPORTANT: replace this with the actual revision ID of your generated
# "initial schema" migration before running `alembic upgrade head`.
# Placeholder left as None to make an unset chain fail loudly (Alembic
# will raise a clear error) rather than silently applying against the
# wrong base revision.
down_revision: Union[str, Sequence[str], None] = "49a711d3f09e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Revoke UPDATE and DELETE on audit_logs from the currently-connected
    role, making the table insert-only (plus SELECT for reads) at the
    database level.
    """
    op.execute("REVOKE UPDATE, DELETE ON audit_logs FROM CURRENT_USER;")


def downgrade() -> None:
    """
    Restore UPDATE/DELETE privileges. Provided for completeness (Alembic
    migrations should always be reversible), but downgrading this
    specific migration should be treated as a deliberate, audited
    security-posture change in a real banking deployment, not a routine
    rollback.
    """
    op.execute("GRANT UPDATE, DELETE ON audit_logs TO CURRENT_USER;")
